### ISSUE TITLE
validate script

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/fa18-516-21#6]
see if we ahave a validate script in the handbook, if not add to the appropriate section

**Comment by MihirNS** [comment]
“21.1.7 How to check if a yaml file is valid?” mentions script location. I will update it with script content and explain prerequisites (i.e do pip install ruamel.yaml before running script) then I will check in script to book repo and update url in epub

Is that ok?

**Comment by laszewsk** [comment]
that is ok. I had actually intermittently some issues with ruaml. However, I have recently used oyaml and that did not have version issues. The best tool I know of is actually yamllint

**Comment by MihirNS** [comment]
Raised PR : https://github.com/cloudmesh-community/book/pull/140
